### ISSUE TITLE
Not working for arch linux on pi 2

### ISSUE THREAD

**Issue by ric96** [davidsblog/rCPU#1]
[root@alarmpi rCPU]# make
xxd -i index.html index.h
make: xxd: Command not found
Makefile:11: recipe for target 'index.h' failed
make: **\* [index.h] Error 127
[root@alarmpi rCPU]#

**Comment by spideynn** [comment]
@ric96 Since you are running Arch Linux, try installing xxd by using `pacman -S xxd`

**Comment by ric96** [comment]
does not work :(

[root@alarmpi ~]# pacman -S git make gcc xxd
error: target not found: xxd
[root@alarmpi ~]#

**Comment by ric96** [comment]
worked with 
pacman -S vim
