### ISSUE TITLE
How to reinstall ?

### ISSUE THREAD

**Issue by Toshibass** [davidsblog/rCPU#4]
Hi ... rCPU is really brilliant and I have it working on several pi's, however I had a problem with static ip address (raspberry pi2 it had 2 ip addresses)  I sorted that our, but now rCPU does not work, 
example: sudo ./rcpu 80 ... htpp://xxx.xxx.x.xx:80  - This web page is not available
I convince myself that I need to rei-install rCPU but even after deleting the files and folder when I try to install again I get ... make: 'rcpu' is up to date.
I am manually installing rCPU with sudo make not as a service with sudo make install
How can I un-make or de install the current rCPU installation so that I can re-install it again.

Thanks for your help on this

Toshi Bass

**Comment by davidsblog** [comment]
This should do the trick, from inside the rCPU/rCPU/ directory:
`sudo make uninstall`
`sudo make clean`
Then you can re-compile from sources again (I am suggesting **sudo make uninstall** just in case).

**Comment by Toshibass** [comment]
Thanks that did it and it's working fine now

Cheers. Toshi

**Comment by davidsblog** [comment]
Great, glad that you have it working again.
