### ISSUE TITLE
unable to uninstall 

### ISSUE THREAD

**Issue by dtan84** [davidsblog/rCPU#5]
Hello David, 

I was able to download install and run rCPU with no problems. However, I'm unable to uninstall the server at this point, I am sure that I'm in /rCPU/rCPU when I run "sudo make uninstall". Any advice? Please know that I am fairly new to linux and raspberry pi and it is a possibility that it is user error. Any information would be super helpful. 
Many Thanks, 
dtan84

**Comment by dtan84** [comment]
Here is the output that I get when I run sudo make uninstall 
/etc/init.d/rCPU stop
make: /etc/init.d/rCPU: Command not found
Makefile:42: recipe for target 'uninstall' failed
make: **\* [uninstall] Error 127

**Comment by davidsblog** [comment]
Is it possible that you have accidentally edited the `Makefile`?  Try downloading a fresh copy from the GitHub repository and run the command again.  Maybe that might help.
