### ISSUE TITLE
No Graph

### ISSUE THREAD

**Issue by mikecoscia** [davidsblog/rCPU#6]
I just installed rCPU on my Pi2 using your directions.  CPU and temp are showing fine, but there is no graph showing the activity of all four cores.  Did I miss something?  Appreciate any help!

**Comment by davidsblog** [comment]
Hello.  It doesn't sound like you've missed anything, if you are getting the other graphs then it should be installed OK.  I have not heard of this happening before, so thanks for letting me know.

Can I ask what OS you are using?   Is it Raspbian?  What browser are you using to view the graphs?

**Comment by mikecoscia** [comment]
Hey David, thanks for responding.  I'm brand new to Linux and Pi, so my knowledge is very basic.  I am running Raspian and it's the default browser.  Only change I made was switching the default search engine to google.

Sent from Outlook Mobile

**Comment by davidsblog** [comment]
Well I hope you have a great time learning Linux and the Pi.  Enjoy!

I will get a fresh copy of Raspbian and put it on my Pi 2 and test it out, it may take me a few days to get round to that, sorry.

I have to admit that I mainly use rCPU on a different machine, so I normally look at the graphs in Chrome, I have not tried the default browser on the Pi in a long time.  Although since you can see the other graphs I would expect them all to work.

Thanks.

**Comment by mikecoscia** [comment]
No need to apologize, your doing me a favor!  Please take your time.  I know my way around Windows and build my own machines, but Linux is different animal entirely...I have plenty to keep me busy, lol.

Sent from Outlook Mobile

**Comment by davidsblog** [comment]
OK, you are right ... I used the latest Raspbian image and found that the default Epiphany browser refuses to show the graphs.  However, using the Midori browser instead shows the graphs just fine.  This is what I did from the command line to install Midori:

`sudo apt-get install midori`

...and then you'll see the Midori browser as an option under the Internet menu.  It is a shame that Epiphany won't display the graphs.  I have not looked into that yet, but other browsers seem fine.

I hope that helps a little.

**Comment by davidsblog** [comment]
I installed the Epiphany browser on my laptop and the charts display OK.  But unfortunately, it seems that the default Raspbian browser won't display any graphs based on [smoothie charts](http://smoothiecharts.org/).

**Comment by mikecoscia** [comment]
Hey Dave!  Thanks for checking that out, glad it wasn't due to something I
did!  I'll give the midori browser a try, not a fan of Epiphany
anyway...lol.

**Comment by davidsblog** [comment]
Cool, let me know how you get on with that.

**Comment by davidsblog** [comment]
I have just made an update which changes the chart plotting library being used.  This new version should work on the default Raspbian browser.

**Comment by mikecoscia** [comment]
Wow, thanks Dave!  I didn't not expect this level of help...lol.  I will
check it out first chance I get!
