### ISSUE TITLE
Canvas dissapears on latest Android chrome after switching tabs/apps

### ISSUE THREAD

**Issue by joszz** [davidsblog/rCPU#7]
On the latest Chrome for android it can happen that the canvas will dissapear after switching between tabs/apps and switching back to rCPU tab. This seems like a Chrome bug (you can find references about this problem on the web) but since it was bothering me I created a fix for it in my own fork (where I mangled up your project a bit since there's stuff in there that only works on Pi and not on a generic x86/64 Ubuntu box, see https://github.com/joszz/rCPU/tree/master/rCPU). 
This hack works for me;

add this to document onload

```
document.addEventListener("visibilitychange", function () {
    window.dispatchEvent(new Event("resize"));
});
```

PS.
Thanks for this cool tool. I'm creating a project around it where rCPU is part of;
https://github.com/joszz/Chell-PHP-Portal

PS2
My current install is based on the older chart library though (smoothie chart). This might not be a problem with the new one (although I expect it will be, since the whole canvas is gone when this happens)

**Comment by davidsblog** [comment]
I like the look of your homeserver portal...  I'm pleased that you've found rCPU useful.  I didn't know about that Chrome bug when switching tabs or apps.  I will try your fix and see if it works with my latest version with the new charts.

Thanks for letting me know.  All the best.

**Comment by davidsblog** [comment]
So far ... I have not been able to reproduce this on the latest version of rCPU.  Maybe the bug doesn't happen with the new charts.  Or is the Chrome bug intermittent?

**Comment by joszz** [comment]
Nope it's constant for me.
Let me update to your latest version and get back to you. Probably have some time tonight to try that.

**Comment by davidsblog** [comment]
Thanks for your help, hopefully it's OK with the latest version.

**Comment by joszz** [comment]
I checked on your latest version and as you said it's ok with that one.
Personally I like the looks of the graph of te old version better so I'll stick with that one and the fix I implemented for this issue. 
Thanks for the awesome work!
