### ISSUE TITLE
Not working on Raspberry Pi 3 running CentOS

### ISSUE THREAD

**Issue by JonathanBristow** [davidsblog/rCPU#9]
Hi, this is the output I'm getting. 

[root@worker-1 rCPU]# make install
xxd -i index.html index.h
make: xxd: Command not found
make: *** [index.h] Error 127

Any ideas what I should do? I've ensured I have the Development Tools installed.

**Comment by davidsblog** [comment]
Hi, it appears that on CentOS you'll need to manually install the `xxd` utility using your package manager.  Please try installing `xxd` and trying again.  Thanks.

**Comment by JonathanBristow** [comment]
👍
